[package]
name = "pup-core"
version = "0.1.0"
authors = [""]

[dependencies]
serde = "1.0"
serde_yaml = "0.7"
serde_derive = "1.0"

[dependencies.base-logging]
git = "https://github.com/shadowmint/rust-base-logging"
branch = "master"
