tasks_path: tasks
workers_path: bin
tasks:
  - tests.builds.deployment
  - tests.builds.bad
environment:
  foo: bar
  bar: foobar
  userthing: "{{EXT_USERNAME}} -> {{EXT_PASSWORD}}"
  SKIP_STEP: true
  IF_STEP: false